# Generated by Django 3.1.7 on 2021-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='station',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='body',
        ),
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
